import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    dashboard: "Dashboard",
    studentDatabase: "Student Database",
    myProfile: "My Profile",
    kycVerification: "KYC Verification",
    examDesk: "Exam Desk",
    videoInterviews: "Video Interviews",
    interviewOps: "Interview Ops Board",
    driveOps: "Drive Operations",
    applications: "Applications",
    resumeReviewDesk: "Resume Review Desk",
    taskManager: "Task Manager",
    studentTicketing: "Student Ticketing",
    staffAuditTrail: "Staff Audit Trail",
    staffPerformance: "Staff Performance",
    quickActions: "Quick Actions",
    analytics: "Analytics",
    reports: "Reports",
    emailCenter: "Email Center",
    classes: "Classes",
    theme: "Theme",
    contactSupport: "Contact Support",
    login: "Login",
    register: "Register",
    logout: "Logout",
    welcome: "Welcome",
    selectRole: "Select Role",
    emailAddress: "Email Address",
    password: "Password",
    rememberMe: "Remember me",
    forgotPassword: "Forgot Password?",
    enterPortal: "Enter Portal",
    createAccount: "Create Account",
    fullName: "Full Name",
    department: "Department",
    keyFeatures: "Key Features",
    businessHours: "Business Hours",
    successRate: "Success Rate",
    averagePackage: "Average Package",
    totalPlacements: "Total Placements",
    partnerCompanies: "Partner Companies",
    searchPlaceholder: "Search by name, skill or ID...",
    totalStudents: "Total Students",
    placementRate: "Placement Rate",
    activeInterviews: "Active Interviews",
    avgAttendance: "Avg Attendance",
    feesCollected: "Fees Collected",
    resumesBuilt: "Resumes Built",
    videosUploaded: "Videos Uploaded",
    certifiedSkills: "Certified Skills",
    newApplications: "New Applications",
    offersExtended: "Offers Extended",
    getInTouch: "Get in Touch",
    email: "Email",
    phone: "Phone",
    address: "Address",
    supportHours: "Support Hours",
    followUs: "Follow Us:",
    ourMission: "Our Mission",
    ourMissionText: "Generative AI Placement System is dedicated to bridging the gap between talented students and leading employers. We empower institutions with cutting-edge placement management solutions powered by AI that drive success and career growth.",
    ourImpact: "Our Impact",
    ourImpactText: "Successfully placed over 5,000+ students across 500+ leading organizations with a 94% placement rate in 2025.",
    systemOverview: "System Overview",
    topCompanies: "Top Recruiting Companies",
    overview: "Overview",
    controlCenter: "Control Center",
    userDirectory: "User Directory",
    deepAnalytics: "Deep Analytics",
    systemConfig: "System Config",
    auditLogs: "Audit Logs",
    alertCenter: "Alert Center",
    serverStatus: "Server Status",
    jobsAndReqs: "Jobs & Reqs",
    talentPool: "Talent Pool",
    interviews: "Interviews",
    offers: "Offers",
    onboarding: "Onboarding",
    genaiHiringHub: "GenAI Hiring Hub",
    settings: "Settings",
    profile: "Profile",
    companyCalendar: "Company Calendar",
    placementDetails: "Placement Details",
    skills: "Skills",
    certifications: "Certifications",
    attendance: "Attendance",
    performance: "Performance",
    companies: "Companies",
    genaiStudio: "GenAI Studio",
    placements: "Placements",
    interviewExam: "Interview Exam",
    resumeBuilder: "Resume Builder",
    profileUpdate: "Profile Update",
    signOut: "Sign Out",
    studentRiskQueue: "Student Risk Queue"
  },
  hi: {
    dashboard: "डैशबोर्ड",
    studentDatabase: "छात्र डेटाबेस",
    myProfile: "मेरी प्रोफ़ाइल",
    kycVerification: "केवाईसी सत्यापन",
    examDesk: "परीक्षा डेस्क",
    videoInterviews: "वीडियो साक्षात्कार",
    interviewOps: "साक्षात्कार संचालन बोर्ड",
    driveOps: "ड्राइव संचालन",
    applications: "आवेदन",
    resumeReviewDesk: "बायोडाटा समीक्षा डेस्क",
    taskManager: "कार्य प्रबंधक",
    studentTicketing: "छात्र टिकटिंग",
    staffAuditTrail: "स्टाफ ऑडिट ट्रेल",
    staffPerformance: "स्टाफ प्रदर्शन",
    quickActions: "त्वरित कार्रवाई",
    analytics: "विश्लेषण",
    reports: "रिपोर्ट",
    emailCenter: "ईमेल केंद्र",
    classes: "कक्षाएं",
    theme: "थीम",
    contactSupport: "सहायता से संपर्क करें",
    login: "लॉगिन",
    register: "पंजीकरण",
    logout: "लॉगआउट",
    welcome: "स्वागत हे",
    selectRole: "भूमिका चुनें",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड",
    rememberMe: "मुझे याद रखें",
    forgotPassword: "पासवर्ड भूल गए?",
    enterPortal: "पोर्टल में प्रवेश करें",
    createAccount: "खाता बनाएं",
    fullName: "पूरा नाम",
    department: "विभाग",
    keyFeatures: "मुख्य विशेषताएं",
    businessHours: "व्यापारिक घंटे",
    successRate: "सफलता दर",
    averagePackage: "औसत पैकेज",
    totalPlacements: "कुल प्लेसमेंट",
    partnerCompanies: "साझेदार कंपनियां",
    searchPlaceholder: "नाम, कौशल या आईडी द्वारा खोजें...",
    totalStudents: "कुल छात्र",
    placementRate: "प्लेसमेंट दर",
    activeInterviews: "सक्रिय साक्षात्कार",
    avgAttendance: "औसत उपस्थिति",
    feesCollected: "एकत्रित शुल्क",
    resumesBuilt: "बनाए गए बायोडाटा",
    videosUploaded: "अपलोड किए गए वीडियो",
    certifiedSkills: "प्रमाणित कौशल",
    newApplications: "नए आवेदन",
    offersExtended: "विस्तारित प्रस्ताव",
    getInTouch: "सम्पर्क करने का माध्यम",
    email: "ईमेल",
    phone: "फ़ोन",
    address: "पता",
    supportHours: "सहायता के घंटे",
    followUs: "हमारा अनुसरण करें:",
    ourMission: "हमारा लक्ष्य",
    ourMissionText: "जेनरेटिव एआई प्लेसमेंट सिस्टम प्रतिभाशाली छात्रों और अग्रणी नियोक्ताओं के बीच की खाई को पाटने के लिए समर्पित है। हम संस्थानों को एआई द्वारा संचालित अत्याधुनिक प्लेसमेंट प्रबंधन समाधानों के साथ सशक्त बनाते हैं जो सफलता और करियर के विकास को बढ़ावा देते हैं।",
    ourImpact: "हमारा प्रभाव",
    ourImpactText: "2025 में 94% प्लेसमेंट दर के साथ 500+ से अधिक अग्रणी संगठनों में 5,000+ से अधिक छात्रों को सफलतापूर्वक स्थान दिया गया।",
    systemOverview: "सिस्टम अवलोकन",
    topCompanies: "शीर्ष भर्ती कंपनियां",
    overview: "अवलोकन",
    controlCenter: "नियंत्रण केंद्र",
    userDirectory: "उपयोगकर्ता निर्देशिका",
    deepAnalytics: "गहन विश्लेषण",
    systemConfig: "सिस्टम कॉन्फ़िगरेशन",
    auditLogs: "ऑडिट लॉग",
    alertCenter: "अलर्ट केंद्र",
    serverStatus: "सर्वर स्थिति",
    jobsAndReqs: "नौकरियां और आवश्यकताएं",
    talentPool: "प्रतिभा पूल",
    interviews: "साक्षात्कार",
    offers: "प्रस्ताव",
    onboarding: "ऑनबोर्डिंग",
    genaiHiringHub: "जेन-एआई भर्ती हब",
    settings: "सेटिंग्स",
    profile: "प्रोफ़ाइल",
    companyCalendar: "कंपनी कैलेंडर",
    placementDetails: "प्लेसमेंट विवरण",
    skills: "कौशल",
    certifications: "प्रमाणपत्र",
    attendance: "उपस्थिति",
    performance: "प्रदर्शन",
    companies: "कंपनियां",
    genaiStudio: "जेन-एआई स्टूडियो",
    placements: "प्लेसमेंट",
    interviewExam: "साक्षात्कार परीक्षा",
    resumeBuilder: "बायोडाटा निर्माता",
    profileUpdate: "प्रोफ़ाइल अद्यतन",
    signOut: "साइन आउट",
    studentRiskQueue: "छात्र जोखिम कतार"
  },
  te: {
    dashboard: "డాష్‌బోర్డ్",
    studentDatabase: "విద్యార్థి డేటాబేస్",
    myProfile: "నా ప్రొఫైల్",
    kycVerification: "కేవైసీ ధృవీకరణ",
    examDesk: "పరీక్ష డెస్క్",
    videoInterviews: "వీడియో ఇంటర్వ్యూలు",
    interviewOps: "ఇంటర్వ్యూ కార్యకలాపాల బోర్డు",
    driveOps: "డ్రైవ్ కార్యకలాపాలు",
    applications: "దరหัสులు",
    resumeReviewDesk: "రెజ్యూమ్ సమీక్ష డెస్క్",
    taskManager: "టాస్క్ మేనేజర్",
    studentTicketing: "విద్యార్థి టికెటింగ్",
    staffAuditTrail: "స్టాఫ్ ఆడిట్ ట్రైల్",
    staffPerformance: "స్టాఫ్ పనితీరు",
    quickActions: "త్వరిత చర్యలు",
    analytics: "విశ్లేషణలు",
    reports: "నివేదికలు",
    emailCenter: "ఈమెయిల్ కేంద్రం",
    classes: "తరగతులు",
    theme: "థీమ్",
    contactSupport: "సహాయం కోసం సంప్రదించండి",
    login: "లాగిన్",
    register: "నమోదు",
    logout: "లాగ్ అవుట్",
    welcome: "స్వాగతం",
    selectRole: "పాత్రను ఎంచుకోండి",
    emailAddress: "ఈమెయిల్ చిరునామా",
    password: "పాస్‌వర్డ్",
    rememberMe: "నన్ను గుర్తుంచుకో",
    forgotPassword: "పాస్‌వర్డ్ మర్చిపోయారా?",
    enterPortal: "పోర్టల్‌లోకి ప్రవేశించండి",
    createAccount: "ఖాతా సృష్టించండి",
    fullName: "పూర్తి పేరు",
    department: "విభాగం",
    keyFeatures: "కీలక ఫీచర్లు",
    businessHours: "పని వేళలు",
    successRate: "విజయవంతమైన రేటు",
    averagePackage: "సగటు ప్యాకేజీ",
    totalPlacements: "మొత్తం ప్లేస్‌మెంట్లు",
    partnerCompanies: "భాగస్వామ్య కంపెనీలు",
    searchPlaceholder: "పేరు, నైపుణ్యం లేదా ఐడి ద్వారా వెతకండి...",
    totalStudents: "మొత్తం విద్యార్థులు",
    placementRate: "ప్లేస్‌మెంట్ రేటు",
    activeInterviews: "క్రియాశీల ఇంటర్వ్యూలు",
    avgAttendance: "సగటు హాజరు",
    feesCollected: "ఫీజు వసూలు",
    resumesBuilt: "తయారు చేసిన రెజ్యూమ్‌లు",
    videosUploaded: "అప్‌లోడ్ చేసిన వీడియోలు",
    certifiedSkills: "ధృవీకరించబడిన నైపుణ్యాలు",
    newApplications: "కొత్త దరఖాస్తులు",
    offersExtended: "ఆఫర్లు",
    getInTouch: "మమ్మల్ని సంప్రదించండి",
    email: "ఈమెయిల్",
    phone: "ఫోన్",
    address: "చిరునామా",
    supportHours: "మద్దతు వేళలు",
    followUs: "మమ్మల్ని అనుసరించండి:",
    ourMission: "మా లక్ష్యం",
    ourMissionText: "జనరేటివ్ AI ప్లేస్‌మెంట్ సిస్టమ్ ప్రతిభావంతులైన విద్యార్థులకు మరియు ప్రముఖ యజమానులకు మధ్య అంతరాన్ని తగ్గించడానికి అంకితం చేయబడింది. మేము సంస్థలకు AI ఆధారిత అత్యాధునిక ప్లేస్‌మెంట్ మేనేజ్‌మెంట్ పరిష్కారాలను అందిస్తాము.",
    ourImpact: "మా ప్రభావం",
    ourImpactText: "2025లో 94% ప్లేస్‌మెంట్ రేటుతో 500 కంటే ఎక్కువ ప్రముఖ సంస్థల్లో 5,000 కంటే ఎక్కువ మంది విద్యార్థులను విజయవంతంగా ఉంచాము.",
    systemOverview: "వ్యవస్థ అవలోకనం",
    topCompanies: "టాప్ రిక్రూటింగ్ కంపెనీలు",
    overview: "అవలోకనం",
    controlCenter: "నియन्त्रణ కేంద్రం",
    userDirectory: "వినియోగదారుల డైరెక్టరీ",
    deepAnalytics: "లోతైన విశ్లేషణ",
    systemConfig: "సిస్టమ్ కాన్ఫిగరేషన్",
    auditLogs: "ఆడిట్ లాగ్‌లు",
    alertCenter: "అలర్ట్ కేంద్రం",
    serverStatus: "సర్వర్ స్థితి",
    jobsAndReqs: "ఉద్యోగాలు & అవసరాలు",
    talentPool: "టాలెంట్ పూల్",
    interviews: "ఇంటర్వ్యూలు",
    offers: "ఆఫర్లు",
    onboarding: "ఆన్‌బోర్డింగ్",
    genaiHiringHub: "జెన్-AI హైరింగ్ హబ్",
    settings: "సెట్టింగులు",
    profile: "ప్రొఫైల్",
    companyCalendar: "కంపెనీ క్యాలెండర్",
    placementDetails: "ప్లేస్‌మెంట్ వివరాలు",
    skills: "నైపుణ్యాలు",
    certifications: "ధృవీకరణ పత్రాలు",
    attendance: "హాజరు",
    performance: "పниతీరు",
    companies: "కంపెనీలు",
    genaiStudio: "జెన్-AI స్టూడియో",
    placements: "ప్లేస్‌మెంట్లు",
    interviewExam: "ఇంటర్వ్యూ పరీక్ష",
    resumeBuilder: "రెజ్యూమ్ బిల్డర్",
    profileUpdate: "ప్రొఫైల్ అప్‌డేట్",
    signOut: "సైన్ అవుట్",
    studentRiskQueue: "విద్యార్థి ప్రమాద క్యూ"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('website_language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('website_language', language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageSelector = ({ currentColors }) => {
  const { language, setLanguage } = useLanguage();

  return (
    <select
      value={language}
      onChange={(e) => setLanguage(e.target.value)}
      style={{
        backgroundColor: currentColors?.input || 'rgba(255,255,255,0.05)',
        borderColor: currentColors?.border || 'rgba(255,255,255,0.1)',
        color: currentColors?.text || '#ffffff'
      }}
      className="rounded-xl border px-3 py-2 text-xs font-bold outline-none focus:ring-2 ring-indigo-500 cursor-pointer"
    >
      <option value="en">🇺🇸 English</option>
      <option value="te">🇮🇳 తెలుగు (Telugu)</option>
      <option value="hi">🇮🇳 हिंदी (Hindi)</option>
    </select>
  );
};
